version: '3'
services:
  mariadb:
    image: mariadb
    volumes:
      - data-mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=myapp_development
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3307:3306"
  comicazi:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    tty: true
    stdin_open: true
volumes:
  data-mysql:
    driver: local